// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3VB5x3aLts-GbExz3jaTlUfN51Mw0uQY',
    appId: '1:416564911767:web:9cf13fb89aa941915b13d2',
    messagingSenderId: '416564911767',
    projectId: 'charo-app-8133e',
    authDomain: 'charo-app-8133e.firebaseapp.com',
    storageBucket: 'charo-app-8133e.firebasestorage.app',
    measurementId: 'G-ZQKQW1Q28S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATvaFRG5GXAleFw92NmOd_3ayCpzi-yh4',
    appId: '1:416564911767:android:01ab19f7c95e30eb5b13d2',
    messagingSenderId: '416564911767',
    projectId: 'charo-app-8133e',
    storageBucket: 'charo-app-8133e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvy2vUtQ-pgHalcTVij-5N5BbfGJRLg0I',
    appId: '1:416564911767:ios:3d28c843e84e437d5b13d2',
    messagingSenderId: '416564911767',
    projectId: 'charo-app-8133e',
    storageBucket: 'charo-app-8133e.firebasestorage.app',
    iosBundleId: 'com.example.charo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvy2vUtQ-pgHalcTVij-5N5BbfGJRLg0I',
    appId: '1:416564911767:ios:3d28c843e84e437d5b13d2',
    messagingSenderId: '416564911767',
    projectId: 'charo-app-8133e',
    storageBucket: 'charo-app-8133e.firebasestorage.app',
    iosBundleId: 'com.example.charo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3VB5x3aLts-GbExz3jaTlUfN51Mw0uQY',
    appId: '1:416564911767:web:13ac12ca254a8b305b13d2',
    messagingSenderId: '416564911767',
    projectId: 'charo-app-8133e',
    authDomain: 'charo-app-8133e.firebaseapp.com',
    storageBucket: 'charo-app-8133e.firebasestorage.app',
    measurementId: 'G-54LC23WGRT',
  );
}